### PR TITLE
Extension to provide shorter XML dialect for POM by using attributes

### PR DESCRIPTION
**Pull request by sveryovka**
# Overview

Initial commit of extension is to provide shorter XML dialect for POM by using XML attributes for dependency and plugin definition.

For example
```
 <dependencies>
    <dependency groupId="junit" artifactId="junit" version="3.8.1" scope="test"/>
  </dependencies>
...
  <plugin artifactId="maven-surefire-plugin">
            <configuration>
              <systemProperties combine.children="append">
                <property>
                  <name>maven.repo.local</name>
                  <value>${maven.repo.local}</value>
                </property>
              </systemProperties>
            </configuration>
          </plugin>
```
Attributes are used only in these 2 places. 

# Examples
There is more complete example at
https://github.com/sveryovka/polyglot-maven/blob/polyglot-xml/polyglot-xml/src/test/resources/pom/pom_maven_v4_1.xml 
and XSD for new dialect at 
https://github.com/sveryovka/polyglot-maven/blob/polyglot-xml/polyglot-xml/src/main/resources/xsd/4.1.0/maven-polyglot-4.1.0.xsd.

Motivation for this was following:
1. I guess most people are generally fine with xml format of pom.xml except that for some quite complex project it becomes quite verbose
2. Dependency definition is most often used element of pom.xml and shorter syntax for dependency can make most of pom.xml files less verbose and more easily readable
3. I know that at some point of time usage of xml attributes was discussed as a posible feature for some future releases

# Problem
Since pom.xml file name is already reserved I had to use different file extension (`pom.xml41`) which is ugly but much safer compared to let's say pom41.xml (which is a bit ugly anyway). 

# Feedback
Since I have played with this for some time and have it ready on github I decided to get some feedback about such XML syntax. Is it interesting at all? Or is this to close to the original formal and it will make more sense to use XML attributes in many other places?

### CODE REVIEW

**Comment by abashev** [comment]
@sveryovka I found your pull request then I've tried to write down something like that. Absolutely :+1:  from my side. But I have one more suggestion - all these version placeholders always driving me nuts and maybe will be more useful to make auto-resolving for properties like ```<group>:<artifact>``` or create one more tag

```
<versions>
  <test-group:test-artifact>1.0.0</test-group:test-artifact>
</versions>
```

**Comment by jvanzyl** [comment]
I've provided you with access to the project. All looks good to me, so merge as you wish. Thanks!

**Comment by fbricon** [comment]
I haven't tried it but yet, I can comment about the filename :-)
First, I think it's important we keep the xml extension, so it will open with XML editors by default. Now for the name itself, I'm really not fond of pom41.xml, I was thinking something like xpom.xml or pomx.xml, the x meaning extra. So the idea to convey here is that this is like a superset of the pom.xml. I reckon this is not ideal either, maybe someone can come up with a better solution.
Anyway, this is just my personal feeling, I won't object to merging the PR as-is.

**Comment by jvanzyl** [comment]
I'm sure we can fix it up before releasing. @sveryovka just did the work so I wanted him to be able to push it in, take comments and fix it up himself. The POM naming needs to be altered I think but need to make a few tweaks to the core.

**Comment by sveryovka** [comment]
I really hate "pom.xml41" name as well. There were some problems with using something.xml. Since it was some time ago I do not remember all the details. I will check and update comments.

What I also want to ask you are some comments on whether you think it is better to use xml attributes (for shorter syntax) in many other places (e.g. contributor, scm, issueManagement and other tags) in addition to dependency and plugin definition or limit usage of attributes to just these 2 tags (dependency and plugin definition). Is limited usage of xml attributes make alternative xml syntax interesting at all? Or is this to close to the original formal and it will make more sense to use XML attributes in many other places?

**Comment by abashev** [comment]
Why it can't be new pom model version like `<modelVersion>5.0.0</modelVersion>` or so?

**Pull request merged**
