### PR TITLE
Added support for nested lists

### PR DESCRIPTION
**Pull request by callmetango**
* added support for nested lists of the Maven ConfigurationContainers Plugin, PluginExecution, ReportPlugin and ReportSet
* reworked and fixed ModelConstructor.ConstructXpp3Dom to emit the appropriate Xpp3Dom nodes containing intermediate child nodes to hold the list items based on the name of the container node
* added read support for explicit !!pairs type to specify child node names that cannot be automatically derived from the container node name
* reworked ModelRepresenter to emit the correct YAML list structures for nested lists (instead of emitting broken YAML maps)
* added tests for the above changes
* fixed test fixtures pom.xml, pom.yaml and generated-pom.yaml to represent valid lists
* bumped version of snakeyaml to latest stable 1.17

### Transforming YAML Lists into Maven Xpp3Dom Nodes

It will transform any YAML list that has a property key with suffix 's' or 'ies' to a Maven Xpp3Dom structure used by [`ConfigurationContainer.configuration`](https://maven.apache.org/ref/3.3.9/maven-model/apidocs/org/apache/maven/model/ConfigurationContainer.html) such as `Plugin` and `PluginExecution` consisting of the appropriate container node and child nodes. An example:
~~~ yaml
configuration:
  libs:
    - ${java.home}/lib/rt.jar
    - ${java.home}/lib/jsse.jar
~~~
will be transformed into
~~~ xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <libs>
    <lib>${java.home}/lib/rt.jar</lib>
    <lib>${java.home}/lib/jsse.jar</lib>
  </libs>
  <anotherKey>anotherValue</anotherKey>
</configuration>
~~~
The name of the intermediate child nodes will be derived from the name of the parent node. So as shown in the example above `libs` will contain `lib` child nodes according to the established Maven conventions.

For mapping non-conforming lists YAMLs own explicit `!!pairs` type can be used like so:
~~~ yaml
configuration:
  scalarParent: !!pairs
    - scalarChild: 36
    - scalarChild: 45
~~~
which gives
~~~ xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <scalarParent>
    <scalarChild>36</scalarChild>
    <scalarChild>45</scalarChild>
  </scalarParent>
</configuration>
~~~

### Transforming Maven Xpp3Dom Nodes into YAML Lists

Transforming Maven Xpp3Dom Nodes into YAML Lists is also supported. It just the other way round as described above. Explicit `!!pairs` will not be generated as I am not aware of a use case right now.

## Tests

See the reworked `Issue44NestedListsTest` and the newly added `Issue62ShadePluginConfigurationTest` in the changed files list. The files `pom.xml`, `pom.yaml` and `generated-pom.yaml` were also touched to represent valid YAML lists in the configuration sections.

## Affected Issues

This pull request fixes issue #44 "polyglot-yaml does not handle nested lists" and partially issue #62 "[polyglot-yaml] does not handle shade plugin".

## Thoughts, Ideas, Comments

I look forward to hearing from you. Maybe the automagic of deriving the child node names is a bit too adventurous. Just tell me and we'll find a solution. :-)

### CODE REVIEW

**Comment by mosabua** [comment]
Any feedback from @takari/polyglot about merging this? I am close to getting a new release out.

**Comment by callmetango** [comment]
@mosabua Nope, no feedback after all the waiting. I noticed you preparing a release and I was very glad to have my proposed changes to be included. Any ideas?

**Comment by mosabua** [comment]
Wdyt @asomov  .. it looks good to me and I am planning to merge unless you have any objections.

**Comment by callmetango** [comment]
@mosabua Thanks for merging!

**Comment by powerslider** [comment]
Hi guys, when are you going to do a release, because I desperately need this fix, especially with when using ```excludes``` and ```includes``` and will that actually work with them?

**Comment by mosabua** [comment]
https://github.com/takari/polyglot-maven/issues/125

**Comment by callmetango** [comment]
@powerslider Just have a look at [polyglot-yaml/src/test/resources/issue44-maven-resources.yaml](https://github.com/takari/polyglot-maven/commit/9dca09a30d290230cb31150bf62fce783d3f7d9b#diff-87d1a3278b264106d0d7c318012f32c2) for an example configuration of the Maven Resources plugin. So yes this should work. :wink:

**Pull request merged**
