### PR TITLE
Fix #198

### LINKED ISSUE #198: org.sonatype.maven.polyglot.PolyglotModelManager.locatePom(File) return null in some cases
The Javadoc for the method states:
@return The path to the (possibly non-existent) POM file, never {@code null}

but if no mapping is found null is returned.

### PR DESCRIPTION
**Pull request by laeubi**

### CODE REVIEW

**Comment by laeubi** [comment]
@mosabua can you review this?

**Comment by laeubi** [comment]
Anything I can do to get this reviewed/merged?

**Comment by mosabua** [comment]
Looks good. I will try to merge and get a release out later this week (not merging so I dont forget release notes entry...)

**Comment by mosabua** [comment]
0.4.6 is out

**Pull request merged**
