### PR TITLE
Use the improved Kotlin scripting implementation instead of JSR-223 ScriptEngine

### PR DESCRIPTION
**Pull request by lion7**
The current polyglot-kotlin implementation uses a JSR-223 `ScriptEngine`  to evaluate the `pom.kts` file.
Since Kotlin 1.3.x the scripting support was improved by using a dedicated scripting host. For details see this KEEP: https://github.com/Kotlin/KEEP/blob/scripting/proposals/scripting-support.md. 

In this PR I re-implemented the script evaluation for Kotlin to use the new scripting host. In the future JetBrains will add support to their IDE which will enable auto-completion support and syntax checking for the `pom.kts` script similiar to Gradle Kotlin scripts.

I also fixed the integration test which referred to an older (non-existing) SNAPSHOT of the polyglot-kotlin core extension. Oddly enough the integration does pass when building because there is also a very basic `pom.xml` in the integration test which does build (I think having a `pom.xml` is required for the `maven-invoker-plugin` to work). 

Note that I removed the bindings for the `MavenProject`, `MavenSession` and `Log` classes. This is now impossible to implement because they are not (yet) available when building the `Model` the first time in the `KotlinModelReader` class. Initially I added them to the DSL class but Kotlin requires non-null instances of those classes which caused the compilation to fail. I've also tried to inject them using the Plexus container but for example the `MavenProject` is not available in the `KotlinModelReader` because the latter is used to create the `MavenProject` instance. To be honest I don't see why you would want to expose these instances in the Kotlin build script anyway, for me it feels like a smell. But please feel free to elaborate.

### CODE REVIEW

**Comment by lion7** [comment]
#67

**Comment by lion7** [comment]
@mosabua could you take a look at this PR? :)

**Comment by thorntonrp** [comment]
> Note that I removed the bindings for the MavenProject, MavenSession and Log classes. This is now impossible to implement because they are not (yet) available when building the Model the first time in the KotlinModelReader class. Initially I added them to the DSL class but Kotlin requires non-null instances of those classes which caused the compilation to fail. I've also tried to inject them using the Plexus container but for example the MavenProject is not available in the KotlinModelReader because the latter is used to create the MavenProject instance. To be honest I don't see why you would want to expose these instances in the Kotlin build script anyway, for me it feels like a smell. But please feel to elaborate.

The MavenProject, MavenSession, and Log are commonly used in maven plugins to get information about the project and the build session in order to use that information to perform necessary tasks during build lifecycle phases. For example, in one of my pom.kts scripts, I use this information so that my script can authenticate with my organization's repository to look up whether there are any updates to core libraries of my project. The bindings don't have to be resolved during the resolution of the model because the execute task does not run during that process (and never should). The execute task is bound to specific Maven lifecycles phases at which time MavenSession, MavenProject, and Log will be available.

**Comment by thorntonrp** [comment]
I've reviewed the diff and I like the core feature of this PR, which is to switch away from the JSR-223 script engine to the Kotlin scripting host. However, I don't think we have to sacrifice allowing scripts to access the MavenProject, MavenSession, and Log. I feel that those are essential features for the execute task that I believe was intended to provide a friendly alternative to traditional Maven plugins.

**Comment by thorntonrp** [comment]
@jnorthrup, @lion7 
I have a fix for this PR that ensures that MavenProject, MavenSession, and Log are resolved for task execution. If this PR is going to be merged, shall I submit another PR that fixes this PR? My changes can be reviewed here: https://github.com/thorntonrp/polyglot-maven/tree/kotlin-scripting-host-enhancements

**Comment by lion7** [comment]
@thorntonrp thanks for your comment and the PR 😄
I was indeed trying to make the bindings available while building the model, which is (as far as I know) impossible. But making them avaiable to tasks only should work I geuss.

My suggestion is to merge your changes in my branch (https://github.com/lion7/polyglot-maven), that way they will be automatically included in this PR. 

Some review notes on your PR:
I see that you created a new class `BuildContext` containing the `MavenProject`, `MavenSession` and `Log` instances. How is this different from the already existing `ExecuteContext` which is already passed to tasks. I think the only change needed is to pass the `ExecuteContext` as an additional implicit receiver when evaluating the task script.

**Comment by lion7** [comment]
@thorntonrp 
I merged your changes in this PR with a few small modifications.
Could you try it out and see if it works for you? 😄

**Comment by lion7** [comment]
(force pushed to update my author info so it now correctly points to my GitHub account)

**Comment by mosabua** [comment]
I am good with merging this provided @thorntonrp and other users / authors of the kotlin dialect are ok with that. We do need a signed Takari CLA as well though

**Comment by lion7** [comment]
@mosabua I sent the signed CLA by email . I'm also curious what @thorntonrp thinks of the current status of this PR.

**Comment by thorntonrp** [comment]
@lion7 @mosabua, This looks really great now. Thank you!

**Comment by mosabua** [comment]
I will merge this shortly and cut a new release .. sounds good?

**Comment by lion7** [comment]
Sounds fine to me :smile:

**Pull request merged**
