### PR TITLE
Upgrade to Maven 3.5.0 and related improvements

### PR DESCRIPTION
**Pull request by mosabua**
Working towards a new release I am upgrading parent pom, Maven version and more. 

DO NOT MERGE YET since there are some issues at the moment.

@ifedorenko @takari/polyglot .. currently this build fails in the polyglot-maven-plugin when run from the parent pom. However when I go into the directory and run the build it works fine. Any idea what could be the issue. It seems to have a class path loading problem since it cant find a class from polyglot-common even though it is in the dependency list:

```
[ERROR] Failed to execute goal io.takari.maven.plugins:takari-lifecycle-plugin:1.12.4:compile (default-compile) on project polyglot-maven-plugin: 20 error(s) encountered:
[ERROR] /media/sf_dev/github/takari/polyglot-maven/polyglot-maven-plugin/src/main/java/org/sonatype/maven/polyglot/plugin/ExecuteMojo.java:[30:8] The import org.sonatype.maven.polyglot.PolyglotModelManager cannot be resolved 
```

Any idea?

### CODE REVIEW

**Comment by mosabua** [comment]
Any idea @ifedorenko ?

**Comment by mosabua** [comment]
@ifedorenko  or @jdillon would you have any idea how to dig into this further? At this stage I am at a loss why it would not work within the reactor but build fine outside the reactor. Next steps is I think to debug the takari-lifecycle-maven-plugin and how it builds up the classpath? Or any other steps?

**Comment by jdillon** [comment]
@mosabua no idea really, not sure what magic the takari lifecycle does which could impact it either

**Comment by mosabua** [comment]
I found that the Maven plugin build works when I change the packaging of the common jar to takari-jar. So I am unblocked again now. Now looking into failures in the ruby module,...

**Comment by mosabua** [comment]
Everything works now. Tested this branch on the polyglot-maven-examples as well. 

I only get a compilation problem with the ruby example. Can you take a look @mkristian maybe? Otherwise I am inclined to merge this to master..

**Comment by mosabua** [comment]
Here is the output I get with the ruby example:

[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ example ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 1 source file to /media/sf_dev/github/takari/polyglot-maven-examples/ruby/example/pkg/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /media/sf_dev/github/takari/polyglot-maven-examples/ruby/example/src/main/java/App.java:[1,37] package org.bouncycastle.jce.provider does not exist
[ERROR] /media/sf_dev/github/takari/polyglot-maven-examples/ruby/example/src/main/java/App.java:[6,20] cannot find symbol
  symbol:   class BouncyCastleProvider
  location: class App
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] gem with jar ....................................... FAILURE [ 38.790 s]
[INFO] ruby ............................................... SKIPPED
[INFO] server ............................................. SKIPPED
[INFO] hello .............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 46.138 s
[INFO] Finished at: 2017-05-05T13:53:40-07:00
[INFO] Final Memory: 34M/204M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project example: Compilation failure: Compilation failure: 
[ERROR] /media/sf_dev/github/takari/polyglot-maven-examples/ruby/example/src/main/java/App.java:[1,37] package org.bouncycastle.jce.provider does not exist
[ERROR] /media/sf_dev/github/takari/polyglot-maven-examples/ruby/example/src/main/java/App.java:[6,20] cannot find symbol
[ERROR]   symbol:   class BouncyCastleProvider
[ERROR]   location: class App
[ERROR] -> [Help 1]

**Comment by mkristian** [comment]
@mosabua please see the PR on examples

**Comment by mosabua** [comment]
Awesome .. I will pull this in on Monday and work on a new release that week.

**Comment by mosabua** [comment]
Now works on all example projects and the build itself. Will merge and work more towards cleanup and release.

**Pull request merged**
