### PR TITLE
passing ExecutionContext into groovy inlined plugin

### PR DESCRIPTION
**Pull request by szantopeter**
Fixing issue https://github.com/takari/polyglot-maven/issues/106

### CODE REVIEW

**Comment by szantopeter** [comment]
@mosabua @jvanzyl  @huntc any thoughts?

**Comment by jvanzyl** [comment]
I don't have any issue with this, @mkristian this is how the ruby integration works yes? You have access to the execution context?

**Comment by szantopeter** [comment]
@jvanzyl this is how the Scala integration works

**Comment by szantopeter** [comment]
@jvanzyl thanks for merging. I can only update the examples after this feature is released. How do I get notified when it is done?

**Comment by jvanzyl** [comment]
Watch the repo and you'll see the release commits.

**Comment by mkristian** [comment]
@jvanzyl sorry for the later response: yes, the ruby script has access to the execution context.

any chance of cutting a release soon ! wanted to get jruby build jdk9 ready and for this I would need a new release here.

**Pull request merged**
