### PR TITLE
add missing license headers and file

### PR DESCRIPTION
**Pull request by puntogil**
fix https://github.com/takari/polyglot-maven/issues/63

### CODE REVIEW

**Comment by jvanzyl** [comment]
Did you just use the license-maven-plugin?

**Comment by puntogil** [comment]
No, is not available (or is broken) in Fedora

**Comment by lefou** [comment]
+1 for the `LICENSE` file.

**Comment by mosabua** [comment]
I committed a license file now.  For the headers we will look at license plugin usage in the future instead of the manual add.

**Pull request closed without merging**
