### PR TITLE
Use Travis CI for continuous integration

### PR DESCRIPTION
**Pull request by lefou**
This branch prepares the source tree to be build with Travis CI.

Besides a merge, to benefit from it, the following tasks need to be done:

* Enable Travis / create Travis account for organization takari
* Activate travis builds for polyglot-maven project
* optional: Register pull request hook to have travis builds and GitHub integration for pull requests

### CODE REVIEW

**Comment by mosabua** [comment]
We have an alternative in the pipeline in the near future and will not adopt using Travis at this stage. Stay tuned.

**Comment by lefou** [comment]
Could you be a bit more specific. You told me the same 8 month ago.

**Comment by mosabua** [comment]
Unfortunately not yet - very sorry.

**Comment by lefou** [comment]
Bump. How long is your pipeline?

**Comment by mosabua** [comment]
Long story... I will ping the team again.

**Pull request closed without merging**
