### PR TITLE
Have translator work on all projects in the reactor

### PR DESCRIPTION
**Pull request by Randgalt**
I'm not sure why it doesn't do this currently. But, the translator should act on all projects in the reactor.

### CODE REVIEW

**Comment by Randgalt** [comment]
Any thoughts on this?

**Comment by lefou** [comment]
What about hiding this functionality behind a configurable option that is also accessible via `-D`?

Example:
```
mvn io.takari.polyglot:polyglot-translate-plugin:translate \
  -Dinput=pom.xml -Doutput=pom.{format} -Drecursive=true
```

**Comment by Randgalt** [comment]
That's OK with me. Thought I can't think of a reason not to do recursive.

**Comment by lefou** [comment]
When using this to just read a pom in another format. Or more generally, whenever this plugin is not used to convert the whole project. I even used it to (temporaily) "normalize" a project, e.g. remove all variable cruft: `mvn ...:translate -Dinput=pom.scala -Doutput=pom-sanitized.scala`

**Comment by Randgalt** [comment]
I see. So, what should the default value for recursive be?

**Comment by lefou** [comment]
IMHO `false` (which is also the current effect) but maybe @mkristian or @jvanzyl have an opinion?

**Comment by jvanzyl** [comment]
Yes, the most recent version doesn't work correctly. Looking at it now. I must have changed something during the push where we made 5 releases. It should always work recursively and translate all projects.

**Comment by Randgalt** [comment]
OK - this PR fixes it. Alternatively, find the previous version.

**Comment by Randgalt** [comment]
@lefou - you can always limit the projects with the standard "-pl" argument.

**Comment by lefou** [comment]
Indeed, this is a valid option. +1 for this PR as it is.

**Comment by jvanzyl** [comment]
If that's good now I'll cut another release.

**Comment by mkristian** [comment]
@jvanzyl just added a small fix. but also realized that this dumping of the pom.xml and this PR are overlapping features. will have closer look. but good to release from my side.

**Comment by Randgalt** [comment]
When will a new version be released?

**Comment by jvanzyl** [comment]
I can do it now if that's cool with everyone.

**Comment by mkristian** [comment]
yes, would be great to see a new release today ;)

**Comment by jvanzyl** [comment]
Done!

http://repo1.maven.org/maven2/io/takari/polyglot/polyglot-common/0.1.11/

**Comment by mkristian** [comment]
@jvanzyl thanx - will be put in use right away

**Comment by khmarbaise** [comment]
Looks good. Single call will convert the whole tree of pom files...

**Pull request merged**
