### PR TITLE
Update Scala to 2.13.12

### PR DESCRIPTION
**Pull request by lefou**
This PR updates from Scala 2.12 to 2.13. With the update to Scala 2.13.12, which is the latest available Scala 2.x version, `polyglot-scala` should also support Java 21.

I suggest to have this PR and PR https://github.com/takari/polyglot-maven/pull/277 (which updates from Scala 2.11 to 2.12) not in the same release, to give users of `polyglot-scala` a chance to migrate their builds step by step. But TBH, I have no clue how many users we still have.

Along this update, I bumped various dependencies, migrated some Scala syntax and fixed deprecated or removed API call sites. I also fixed some issues with left-open file resources.

### CODE REVIEW

**Comment by cstamas** [comment]
@lefou sorry, but I merged the other PR and now there are quite some conflicts :disappointed:

**Comment by lefou** [comment]
@cstamas I rebased this PR. It's ready for review and merge, although, I'd prefer if you could cut a `0.6.0` release before the merge, and a `0.7.0` release after it, due to the major change in Scala version and it's potential implications for users. Thanks!

**Comment by cstamas** [comment]
So just to clarify:
- release current master as 0.6.0
- merge this PR, release 0.7.0

Pls confirm

**Comment by lefou** [comment]
> So just to clarify:
> 
>     * release current master as 0.6.0
> 
>     * merge this PR, release 0.7.0
> 
> 
> Pls confirm

Exactly that. 👍‍

**Pull request merged**
