### PR TITLE
polyglot-scala: Scala syntax friendly include preprocessor

### PR DESCRIPTION
**Pull request by lefou**
This change adds an alternative preprocessor directive to the scala dialect.

In addition to `#include <file>`, now also `//##include <file>` is supported.
The motivation behind this is, to improve the editing experience. The latter added version produces syntax-correct scala files, which in turn improves editors and IDEs, e.g. parsing, formatting and highlighting. The former version does not.

The unusual long prefix `//##` was choosen, to avoid confusion with a possibly commented out include (e.g. `// #include`).

Also, this change adds a hint how to debug the `pom.scala` script to the error message in case of a compile error.

### CODE REVIEW

**Comment by lefou** [comment]
Any reservations about this PR? 
@huntc, do you mind to take a look?

**Comment by mosabua** [comment]
Sorry .. dropped the ball on this. Looks good to me but I have limited insight into the scala version..

**Comment by huntc** [comment]
I can take a look shortly. Thanks.

**Comment by huntc** [comment]
I'm unsure still as to why the two types of include are required. Is the new one backwardly compatible?

**Comment by lefou** [comment]
The first and older (`#include`) is the backward compatible one. It's the default of Twitters eval util.

The other new one is not backward compatible but results in proper Scala syntax, which makes a huge difference IMHO. All IDEs and editors can syntax highlight and format the latter files out of the box.

**Comment by lefou** [comment]
If you suggest to go with only one include type, I would choose `//##include`. But it would require to migrate a whole Maven project at once, after the version bump. In that case, it could make sense the make it one character shorter: `//#include`.

**Comment by lefou** [comment]
Any other questions? Are we ready to merge?

**Comment by mosabua** [comment]
Its up to you guys. I am good merging as is.

**Comment by huntc** [comment]
My inclination is to go with just #include. I’d prefer that we have just one form of inclusion to reduce confusion. It isn’t obvious to the regular user why there should be two forms. If the new implementation breaks compatibility then we should either bump the major version of the project or provide a flag that disables the new functionality until we are ready to do the major version bump.

**Comment by mosabua** [comment]
I am fine with bumping to 0.3.0 or given it is used in production in various places even to 1.0.0 ..

**Comment by lefou** [comment]
I think 0.3.0 would enough for the change, as semantic versioning defines major bumps only for versions >= 1. On the other hand, polyglot-maven is very stable in my daily work, so 1.0.0 is definitely ok too (but I can speak mostly for core and scala).

I will push another commit, which removes the `#include`. You can merge just before the bump.

Apart from the well informed user who knows the internals of polyglot-scala and twitter eval, I guess there are not much users who already know or use the `#include`. So I expect the impact of that change isn't that great. But the change will definitely improve acceptance.

**Comment by huntc** [comment]
Thanks for the dialogue. 

Isn’t #include nicer to look at rather than //#include ?

**Comment by lefou** [comment]
The `#include` isn't proper Scala syntax. As a consequence, the editor cannot parse the file without errors. Thus no syntax highlighting, no formatting.

**Comment by huntc** [comment]
Oh, I got it - thanks for the explanation. I'm good to go.

**Comment by huntc** [comment]
I also agree that a 0.3.0 is fine for a release. Thanks for involving me guys, and thanks for the hard work @lefou.

**Comment by huntc** [comment]
Oops - I think I merged prior to CI completing... I think there's a CI error also... Apologies.

**Comment by mosabua** [comment]
No worries. All good. I will move towards a release in the next days.

**Comment by mosabua** [comment]
Build passed on master for me..

**Pull request merged**
