### PR TITLE
Rework script evaluation so auto-completion works in IntelliJ IDEA

### PR DESCRIPTION
**Pull request by lion7**
The script evaluator used an implicit receiver to make the DSL available to the Kotlin pom script.
I discovered today that this isn't necessary and that it's also possible to pass the script file and project/model as constructor arguments to the compiled script instead.
Combined with the `@ScriptTemplateDefinition` annotation this will enable auto-completion in IntelliJ IDEA. 

Note that for auto-completion to work it is necessary that the `polyglot-kotlin` JAR and its dependencies are on the compile classpath so IntelliJ IDEA will index them. The easiest way to archieve this without changing your project's dependencies is to add it as a global library (after installing it to your local maven repo first 😉). To do this open `Project Structure` (Ctrl+Alt+Shift+S) -> `Global Libraries` -> click the `+` sign and choose `From maven...`. Fill in `io.takari.polyglot:polyglot-kotlin:0.4.2-SNAPSHOT`, check the `Sources` checkbox and press `OK`. Add it to your (IntelliJ) module and auto-completion should work 😄

### CODE REVIEW

**Comment by lion7** [comment]
@mosabua could you take a look at this?

**Comment by mosabua** [comment]
I was not aware of this PR. Somehow missed it. Let me look, merge and cut a release some time this week. Provided you think its ready...

**Comment by lion7** [comment]
That's okay, I never mentioned it when it was created :wink:

Today I'll update the readme to describe how to enable the auto completion support. After that I think it's ready to merge.

**Comment by lion7** [comment]
I updated the README and checked the unit tests + integration tests.
The example in https://github.com/takari/polyglot-maven-examples also still works :smile: 

Could you let me know if this is released? I'm currently writing a blog post about using `polyglot-kotlin` and would like to refer to the released version instead of a snapshot :wink:

**Comment by mosabua** [comment]
I can get this released tomorrow or latest Friday.

**Comment by lion7** [comment]
Sounds great, in that case I'll wait with publishing the blog until the release is here :smile:

**Pull request merged**
