### PR TITLE
Use alternative target path for compiled pom model

### PR DESCRIPTION
**Pull request by lefou**
With this change, we no longer store the compiled class files from `pom.scala` under `target`, but use a dedicated `.mvn.polyglot` dir. 

Motivation: Typical repeated maven runs include the `clean` goal, which removes the `target` dir. This means, we need to re-compile all `pom.scala` files in the next run, which cost's a lot of time.

### CODE REVIEW

**Comment by mosabua** [comment]
This is going to force users to upgrade the gitignore file and kinda goes against the whole idea of having a target directory. Nobody is forcing the users to use clean... it should just work with mvn install and whatever.. so I am not sure we want to do this. Wdty @jvanzyl

**Comment by lefou** [comment]
Yeah, that's understandable, but again it's is a huge time saver. Maybe, this can be an opt-in configurable feature. Controlling it via a sys property comes to mind (e.g. `-Dpolyglot.outputdir=.mvn.polyglot`), which could be made persistent via `.mvn/maven.config`. WDYT? Is there some better way to configure a Maven core extension?

**Comment by mosabua** [comment]
as an option that would be fine imho .. we either have to implement in all dialects or use a specific name

polyglot.scala.outputdir ?

**Comment by lefou** [comment]
@mosabua I made the necessary changes. The property is `polyglot.scala.outputdir`, as you suggested.

**Comment by mosabua** [comment]
Great. I think we have to document that somewhere and maybe also activate it in the examples project .. I will merge and play with it

**Comment by mosabua** [comment]
Added example config now.

**Pull request merged**
