### PR TITLE
Minimize 'locatePom()'-calls in PolyglotModelManager

### PR DESCRIPTION
**Pull request by HannesWell**
For some Mapping implementations calling `locatePom()` can be a relatively expensive operation, for example because it includes many file-system interactions.

Because only the result of the mapping with the highest priority is returned eventually, `findPom()` and `determineFlavourFromPom()` can be speed-up if Mappings are processed in descending priority-order and simply return the first encountered result. Just like the other get*() methods do.

Additionally this PR simplifies the implementation of `getSortedMappings()` at bit.

### CODE REVIEW

**Comment by HannesWell** [comment]
@jvanzyl can you please have a look at this PR?

**Comment by HannesWell** [comment]
Thank you @fbricon do you know of any plans about the next release that contains this change?
And are there snapshot builds available anywhere?

**Comment by jvanzyl** [comment]
@HannesWell I just made a release, should be in Maven Central shortly.

**Comment by HannesWell** [comment]
Great! Thank you.

**Pull request merged**
