### PR TITLE
polyglot-scala: Added default value for pom property modelversion (4.0.0)

### PR DESCRIPTION
**Pull request by lefou**
It is more than expected, that this version will not change in the near future.

### CODE REVIEW

**Comment by mosabua** [comment]
Merged with https://github.com/takari/polyglot-maven/commit/f765ca461917b101a04d3b4776afe837efe34bb3

**Comment by mosabua** [comment]
I merged this but I am getting test failures.. wanna have a look @lefou ?

**Comment by lefou** [comment]
Why do you dropped my commits? I see only my github name in your commit message.

**Comment by lefou** [comment]
@mosabua I can reproduce the failing tests. Must have overlooked it, sorry. I'll create another PR.

**Comment by mosabua** [comment]
I screwed up the merging .. sorry

**Comment by lefou** [comment]
Thanks for telling me. That's OK.

I'd be glad to offer my help. I think, I have a fairly good understanding of polyglot-maven and use it in several projects. With commit access I could merge approved or trivial commits directly. WDYT?

**Comment by mosabua** [comment]
Sure.. you would have to sign the Takari CLA .. did you do that already?

**Comment by lefou** [comment]
I'm not sure, I think not. Where can I find it?

**Pull request closed without merging**
